In [1]:
!pip install pandas
!pip install matplotlib
!pip install seaborn


In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.


In [3]:
df = pd.read_csv('/Users/emilysanchez/Desktop/capstone_project/survey_data_updated.csv')

In [4]:
df.head()

ResponseId                                         MainBranch  \
0           2                     I am a developer by profession   
1           3                     I am a developer by profession   
2          10                     I am a developer by profession   
3          11  I used to be a developer by profession, but no...   
4          12                     I am a developer by profession   

               Age                                         Employment  \
0  35-44 years old                                Employed, full-time   
1  45-54 years old                                Employed, full-time   
2  35-44 years old  Independent contractor, freelancer, or self-em...   
3  35-44 years old                                Employed, full-time   
4  45-54 years old                                Employed, full-time   

  RemoteWork                                   CodingActivities  \
0     Remote  Hobby;Contribute to open-source projects;Other...   
1     Remote  Hobby;Contribute to open-source projects;Other...   
2     Remote                           Bootstrapping a business   
3     Remote           Hobby;Contribute to open-source projects   
4  In-person                      Hobby;School or academic work   

                                           EdLevel  \
0     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
1  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
2  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
3     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
4   Professional degree (JD, MD, Ph.D, Ed.D, etc.)   

                                           LearnCode  \
0  Books / Physical media;Colleague;On the job tr...   
1  Books / Physical media;Colleague;On the job tr...   
2  On the job training;Other online resources (e....   
3  Books / Physical media;Other online resources ...   
4  Books / Physical media;School (i.e., Universit...   

                                     LearnCodeOnline YearsCode  ...  \
0  Technical documentation;Blogs;Books;Written Tu...        20  ...   
1  Technical documentation;Blogs;Books;Written Tu...        37  ...   
2  Technical documentation;Blogs;Written Tutorial...        15  ...   
3  Technical documentation;Books;Written Tutorial...        20  ...   
4                                                NaN        30  ...   

  JobSatPoints_4 JobSatPoints_5 JobSatPoints_6 JobSatPoints_7 JobSatPoints_8  \
0            0.0            0.0            0.0            0.0            0.0   
1            NaN            NaN            NaN            NaN            NaN   
2            NaN            NaN            NaN            NaN            NaN   
3            0.0            0.0           25.0           10.0            0.0   
4            NaN            NaN            NaN            NaN            NaN   

  JobSatPoints_9 JobSatPoints_10 JobSatPoints_11 ConvertedCompYearly JobSat  
0            0.0             0.0             0.0                 NaN    NaN  
1            NaN             NaN             NaN                 NaN    NaN  
2            NaN             NaN             NaN                 NaN    NaN  
3           15.0             0.0             0.0                 NaN    8.0  
4            NaN             NaN             NaN                 NaN    NaN  

[5 rows x 98 columns]

In [11]:
df.describe(include='all')

ResponseId                      MainBranch              Age  \
count   18845.000000                           18845            18845   
unique           NaN                               5                8   
top              NaN  I am a developer by profession  25-34 years old   
freq             NaN                           17139             7788   
mean    28819.206315                             NaN              NaN   
std     17541.596002                             NaN              NaN   
min         2.000000                             NaN              NaN   
25%     13747.000000                             NaN              NaN   
50%     27907.000000                             NaN              NaN   
75%     43410.000000                             NaN              NaN   
max     65432.000000                             NaN              NaN   

                 Employment RemoteWork CodingActivities  \
count                 18845      18839            18845   
unique                   60          3              107   
top     Employed, full-time     Remote            Hobby   
freq                  12664       8168             2731   
mean                    NaN        NaN              NaN   
std                     NaN        NaN              NaN   
min                     NaN        NaN              NaN   
25%                     NaN        NaN              NaN   
50%                     NaN        NaN              NaN   
75%                     NaN        NaN              NaN   
max                     NaN        NaN              NaN   

                                             EdLevel  \
count                                          18845   
unique                                             8   
top     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
freq                                            8629   
mean                                             NaN   
std                                              NaN   
min                                              NaN   
25%                                              NaN   
50%                                              NaN   
75%                                              NaN   
max                                              NaN   

                                                LearnCode  \
count                                               18808   
unique                                                358   
top     Other online resources (e.g., videos, blogs, f...   
freq                                                  935   
mean                                                  NaN   
std                                                   NaN   
min                                                   NaN   
25%                                                   NaN   
50%                                                   NaN   
75%                                                   NaN   
max                                                   NaN   

                                          LearnCodeOnline YearsCode  ...  \
count                                               15931     18794  ...   
unique                                               5740        52  ...   
top     Technical documentation;Blogs;Written Tutorial...        10  ...   
freq                                                  190      1560  ...   
mean                                                  NaN       NaN  ...   
std                                                   NaN       NaN  ...   
min                                                   NaN       NaN  ...   
25%                                                   NaN       NaN  ...   
50%                                                   NaN       NaN  ...   
75%                                                   NaN       NaN  ...   
max                                                   NaN       NaN  ...   

       JobSatPoints_4 JobSatPoints_5 JobSatPoints_6 JobSatPoints_7  \
count    12163.000000   12170.00000

In [12]:
df.shape

(18845, 98)

In [14]:
print(df.dtypes)

ResponseId               int64
MainBranch              object
Age                     object
Employment              object
RemoteWork              object
                        ...   
JobSatPoints_9         float64
JobSatPoints_10        float64
JobSatPoints_11        float64
ConvertedCompYearly    float64
JobSat                 float64
Length: 98, dtype: object


since Ages is an object (they are ranges in the survey responses), I will change the ages to be the median value of each category. I will then replace the values in the dataset to be these median ages. 
Note: 'Under 18 years old' will be assumed as 18, '65 years or older' will be assumed as 65, 'Prefer not to say' will be assumed as the median of all these ages (33.0 years old)

In [15]:
unique_ages = df['Age'].unique()
print(unique_ages)

['35-44 years old' '45-54 years old' '25-34 years old' '55-64 years old'
 '18-24 years old' 'Under 18 years old' '65 years or older'
 'Prefer not to say']


In [16]:
df['Age'] = df['Age'].replace('Under 18 years old', 18.0)
df['Age'] = df['Age'].replace('18-24 years old', 21.5)
df['Age'] = df['Age'].replace('25-34 years old', 29.5)
df['Age'] = df['Age'].replace('35-44 years old', 39.5)
df['Age'] = df['Age'].replace('45-54 years old', 49.5)
df['Age'] = df['Age'].replace('55-64 years old', 59.5)
df['Age'] = df['Age'].replace('65 years or older', 65.0)
df['Age'] = df['Age'].replace('Prefer not to say', 33.0)

/var/folders/vd/87t2c1411nv0n60c36h4qkt00000gn/T/ipykernel_40890/1768953484.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Age'] = df['Age'].replace('Prefer not to say', 33.0)


In [19]:
df['Age'] = df['Age'].replace(30.0, 29.5)
mean_age = df['Age'].mean()
print(mean_age)

34.207057574953566


In [21]:
median_age = df['Age'].median()
print(median_age)

29.5


In [22]:
df.describe()

ResponseId           Age       WorkExp  JobSatPoints_1  \
count  18845.000000  18845.000000  12274.000000    12137.000000   
mean   28819.206315     34.207058     11.620336       20.700606   
std    17541.596002      9.749297      8.844735       26.962498   
min        2.000000     18.000000      0.000000        0.000000   
25%    13747.000000     29.500000      5.000000        0.000000   
50%    27907.000000     29.500000     10.000000       10.000000   
75%    43410.000000     39.500000     16.000000       25.000000   
max    65432.000000     65.000000     50.000000      100.000000   

       JobSatPoints_4  JobSatPoints_5  JobSatPoints_6  JobSatPoints_7  \
count    12163.000000    12170.000000    12185.000000    12185.000000   
mean         8.030009       11.988671       25.292684       24.573818   
std         19.114522       23.497413       27.500306       27.686252   
min          0.000000        0.000000        0.000000        0.000000   
25%          0.000000        0.000000        5.000000        5.000000   
50%          0.000000        0.000000       20.000000       15.000000   
75%          6.000000       10.000000       30.000000       30.000000   
max        100.000000      100.000000      100.000000      100.000000   

       JobSatPoints_8  JobSatPoints_9  JobSatPoints_10  JobSatPoints_11  \
count    12191.000000    12184.000000     12187.000000     12182.000000   
mean        22.860208       17.299167        12.217014        11.357700   
std         27.149096       25.901276        24.363271        23.114259   
min          0.000000        0.000000         0.000000         0.000000   
25%          0.000000        0.000000         0.000000         0.000000   
50%         15.000000       10.000000         0.000000         0.000000   
75%         30.000000       20.000000        10.000000        10.000000   
max        100.000000      100.000000       100.000000       100.000000   

       ConvertedCompYearly        JobSat  
count         9.550000e+03  12111.000000  
mean          8.458970e+04      7.145075  
std           1.173856e+05      1.989114  
min           1.000000e+00      0.000000  
25%           3.222200e+04      6.000000  
50%           6.585750e+04      8.000000  
75%           1.100000e+05      8.000000  
max           6.340564e+06     10.000000

Current analysis: Mean age is 34 years old. Median age is 29.5 years old. Upper IQR is 39.5. The majority of survey participants are between 25-44 years old and(using the original age categories in the survey).

In [23]:
print(df.columns) #I need all the column names to continue my analyis

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork',
       'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       'YearsCode', 'YearsCodePro', 'DevType', 'OrgSize', 'Country',
       'LanguageHaveWorkedWith', 'LanguageWantToWorkWith', 'LanguageAdmired',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith', 'DatabaseAdmired',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith', 'PlatformAdmired',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith', 'WebframeAdmired',
       'EmbeddedHaveWorkedWith', 'EmbeddedWantToWorkWith', 'EmbeddedAdmired',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith', 'MiscTechAdmired',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'ToolsTechAdmired', 'NEWCollabToolsHaveWorkedWith',
       'NEWCollabToolsWantToWorkWith', 'NEWCollabToolsAdmired',
       'OpSysPersonal use', 'OpSysProfessional use',
       'OfficeStackAsyncHaveWorkedWith', 'OfficeStackAsyncWantToWorkWith',
       'Off

I will first take a look at who we are suverying

In [28]:
#need to make years coding and years coding pro into ints. 
yctype = df.dtypes.iloc[9]
ycptype = df.dtypes.iloc[10]

print(yctype)
print(ycptype)


object
object


In [32]:
unique_years = df['YearsCode'].unique()
print(unique_years)

unique_yearsPro = df['YearsCodePro'].unique()
print(unique_yearsPro)

['20' '37' '15' '30' '12' '25' '44' '18' '9' '10' '8' '22' '6' '7' '40'
 '39' '11' '35' '34' '13' '14' '5' '19' '31' '17' '16' '43' '28' '4' '26'
 '32' '36' '41' '45' '27' '3' '38' '21' '24' '33' '2' '23' nan '29' '42'
 'More than 50 years' '48' 'Less than 1 year' '47' '46' '49' '1' '50']
['17' '27' '11' nan '25' '10' '18' '37' '12' '6' '7' '8' '14' '4' '3' '1'
 '29' '30' '5' '24' '13' '35' '23' '9' '2' '16' '15' '20' '32' '19' '33'
 'Less than 1 year' '39' '22' '31' '26' '28' '40' '38'
 'More than 50 years' '21' '34' '36' '45' '41' '43' '44' '42' '46' '47'
 '48' '49' '50']


In [40]:
print(df.isnull().sum()) 

ResponseId                0
MainBranch                0
Age                       0
Employment                0
RemoteWork                6
                       ... 
JobSatPoints_9         6661
JobSatPoints_10        6658
JobSatPoints_11        6663
ConvertedCompYearly    9295
JobSat                 6734
Length: 98, dtype: int64


In [33]:
df['YearsCode'] = df['YearsCode'].replace('Less than 1 year', 1)
df['YearsCode'] = df['YearsCode'].replace('More than 50 years', 51)
df['YearsCodePro'] = df['YearsCodePro'].replace('Less than 1 year', 1)
df['YearsCodePro'] = df['YearsCodePro'].replace('More than 50 years', 51)

In [41]:
# Cleaning the NaNs and replacing them with the mean
df['YearsCode'] = pd.to_numeric(df['YearsCode'], errors='coerce')
df['YearsCode'] = df['YearsCode'].fillna(df['YearsCode'].mean())
print(df['YearsCode'].head())

0    20.0
1    37.0
2    15.0
3    20.0
4    30.0
Name: YearsCode, dtype: float64


In [42]:
# Cleaning the NaNs and replacing them with the mean
df['YearsCodePro'] = pd.to_numeric(df['YearsCodePro'], errors='coerce')
df['YearsCodePro'] = df['YearsCodePro'].fillna(df['YearsCodePro'].mean())
print(df['YearsCodePro'].head())

0    17.000000
1    27.000000
2    11.000000
3    10.719962
4    25.000000
Name: YearsCodePro, dtype: float64


In [49]:
avg_years_code = df['YearsCode'].mean()
avg_years_codepro = df['YearsCodePro'].mean()

med_years_code = df['YearsCode'].median()
med_years_codepro = df['YearsCodePro'].median()


In [50]:
print(f"Mean years coding: {avg_years_code}")
print(f"Mean years coding professionally: {avg_years_codepro}")

print(f"Median years coding: {med_years_code}")
print(f"Median years coding professionally: {med_years_codepro}")


Mean years coding: 15.266521230179846
Mean years coding professionally: 10.719962366484031
Median years coding: 13.0
Median years coding professionally: 9.0


In [54]:
mean_comp = df['ConvertedCompYearly'].mean()
median_comp = df['ConvertedCompYearly'].median()

print(f"Average yearly compensation: {mean_comp}")
print(f"Median yearly compensation: {median_comp}")

Average yearly compensation: 84589.6967539267
Median yearly compensation: 65857.5


I will now take a look at the languages the survey respondents work with

In [56]:
df.to_csv('/Users/emilysanchez/Desktop/capstone_project/CLEAN_survey_data_updated.csv', index=False)